#cloud-config

packages-update: true
packages-upgrade: true


runcmd:
    # Update the source list
    - sudo apt-get upgrade

    - sudo apt-get update

    - sudo apt-get install python

    - sudo apt-get install python-pip

    - sudo apt-get install python-psutil

    - sudo apt-get install -y python python-dev python-distribute python-pip python-pymongo
