#cloud-config

packages-update: true
packages-upgrade: true


runcmd:
    # Update the source list
    - sudo apt-get upgrade

    - sudo apt-get update
    - sudo apt-get install python

    - sudo apt-get install python-pip

    - sudo pip install psutil

    - sudo apt-get install python-psutil

    - sudo pip install -U pymongo
