#cloud-config

packages-update: true
packages-upgrade: true


runcmd:
    # Update the source list
    - sudo apt-get upgrade

    - sudo apt-get update

    - sudo apt-get install python

    - sudo apt-get install python-pip

    - sudo apt-get install python-psutil


- sudo apt-get update && apt-get install -y python-dev python-distribute python-pip python-pymongo python-psutil

#Intall docker
sudo aptitude  update
sudo aptitude -y upgrade
sudo aptitude install linux-image-extra-'uname -r'
sudo sh -c "wget -qO- https://get.docker.io/gpg | apt-key add -"
sudo sh -c "echo deb http://get.docker.io/ubuntu docker main\ > /etc/apt/sources.list.d/docker.list"
sudo aptitude update
sudo aptitude install lxc-docker


apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-3.2.list
sudo apt-get update && apt-get install -y mongodb-org
sudo service mongod start
